language: php

php:
  - 8.1

install:
  - if [[ "$DEPS" = 'high' ]]; then  composer install; fi
  - if [[ "$DEPS" = 'low' ]]; then  composer update --prefer-lowest --prefer-stable; fi

script:
  - ./vendor/bin/phpstan analyze -l 9 src
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpunit --testsuite=integration

services:
  - mysql
  - postgresql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS dqo;'
  - psql -c 'create database dqo;' -U postgres

env:
  global:
    - POSTGRES_HOST=127.0.0.1
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=
    - POSTGRES_DATABASE=dqo
    - MYSQL_HOST=127.0.0.1
    - MYSQL_USER=travis
    - MYSQL_PASSWORD=
    - MYSQL_DATABASE=dqo
  jobs:
    - DEPS="low"
    - DEPS="high"
